"""empty message

Revision ID: 349f71a1ff8b
Revises: 7fffc0865cf7
Create Date: 2026-03-03 23:45:51.847289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '349f71a1ff8b'
down_revision = '7fffc0865cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('users_affiliate_number_key'), type_='unique')
        batch_op.drop_column('affiliate_number')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('affiliate_number', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint(batch_op.f('users_affiliate_number_key'), ['affiliate_number'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###
