"""empty message

Revision ID: 9d2398a7ef75
Revises: b096a301a14b
Create Date: 2026-03-25 00:28:39.796299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d2398a7ef75'
down_revision = 'b096a301a14b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('suggested_patient_dni', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_ai_message_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ai_detected_procedure_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ai_detected_specialty_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'specialties', ['ai_detected_specialty_id'], ['id'])
        batch_op.create_foreign_key(None, 'procedures', ['ai_detected_procedure_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ai_detected_specialty_id')
        batch_op.drop_column('ai_detected_procedure_id')
        batch_op.drop_column('last_ai_message_id')

    op.drop_table('ai_suggestions')
    # ### end Alembic commands ###
